### PR TITLE
Update kivy.bat

### PR DESCRIPTION
**Pull request by PeterStone4818**

### CODE REVIEW

**Comment by KeyWeeUsr** [comment]
I'm wondering if you're incapable of understanding the word `no`, or if you're just deranged, Graham(@grahamRuttiman, @izytraxx, @PeterStone4818, @JordanTogo). In both cases, [I've already explained](https://github.com/KeyWeeUsr/KivyInstaller/pull/10#issuecomment-298019759) how to choose whatever version you like without trying to push old version for whatever reason. Multiple accounts won't help you and you just make me smile with these delusional attempts.

**Comment by PeterStone4818** [comment]
To Peter Badida,


Thank you kindly for your amazingly insulting email but unfortunately i am not Graham and simply made a mistake this morning with git hub as i only started using the program for my university studies recently. Regardless i recommend that you  properly identify people before insulting them privately or publicly. I made a change to the document on github as per my lecturers instruction then accidentally tried to push rather then download the branched file. I ASSURE you it was a simple accident due to inexperience with the program.


Thank you for your time and i hope you understand my mistake as i have understood yours. Have a good day.


Yours in truth

Peter Stone

Undergraduate Student, Bachelor of Information Technology.

James Cook University, Townsville Campus

Student ID: 13288651

________________________________

**Comment by KeyWeeUsr** [comment]
I couldn't verify your student ID but if that's the case, Peter, I'm very sorry my response mistakenly targeted you and I apologize to you as I can imagine how unfair it sounds to you if you acted fairly. I admit I sound like an asshole.

Now I'll try to present to you why I thought you were Graham and why this response was so harsh. Since the end of April I received a Pull Request from a person that identified himself like @grahamRuttiman.

image[source](https://github.com/KeyWeeUsr/KivyInstaller/pulls?q=is%3Apr+is%3Aclosed)

I explained to that person why the change he made a Pull Request for was not desired and provided him a [clear way how to customize the program](http://kivyinstaller.readthedocs.io/en/master/gettingstarted.html#defaults)(https://github.com/KeyWeeUsr/KivyInstaller/commit/e05c28188d8581d6c1d0223e19957c1073da727f) for own needs, but few days later he opened **two** such Pull Requests. I didn't really expect that, but I was like - whatever, the guy apparently can't use GitHub - although something definitely stank in there. Then, three days later, another Pull Request with the exact patch. I banned the person hoping for no further intentional spam in my repository as it just looked like I'm incapable of implementing a local config for him (which I did during his first attempt).

image[source](https://github.com/KeyWeeUsr/KivyInstaller/network)

Later, the **exact** change was posted by a "different" person and another change was added to some other account (just open the `Network` tab and look for yourself). I just silently closed it, because it looked like a different person. Now you came to the show and I was rather fed up with this spam :)

image

The identification info you provided in your email signature (I guess?) was very useful to me as I think I found **why** there was the attempt to change to that specific version and that's apparently because of this pretty document:

image[source](https://www.coursehero.com/file/19202741/python-installation/)

which together with these specs makes sense to me - you as a student apparently didn't receive Kivy, nor Python although the fruit guys did, so [you tried](https://duckduckgo.com/?q="kivyinstaller"+"james+cook")(otherwise no such mention about this installer, only about Kivy) as well as you could to find some simple solution to do so. As the version `1.9.1` of Kivy was kind of problematic to use with Python `3.5` and higher. It's rather a mystery to me why the course wasn't updated with the latest stable Kivy version as that one supports `2.7`, `3.4`, `3.5`, `3.6` and might even `3.3`, but I haven't tried it for a long time.

image
[source](https://www.jcu.edu.au/information-and-communications-technology/help-and-support/gatcf/standard-operating-environment)

In any case, I don't really think you will just ignore such a harsh response, however I hope you won't let it victimize you in your doings if it's plain studying of how Kivy or Python work or in your further steps as a developer, as I acted only as the owner of a repository that got spammed since April by a weird kind of person, and not as a core developer of Kivy. Therefore if you are pissed, target your actions on me, not on the framework.

Thank you for your understanding

**Comment by PeterStone4818** [comment]
To Peter Badida,


All good no harm done, i apologise for my rash email as well because it was inappropriate on my behalf. I also apologise for accidentally trying to mess with your repository but i am new to github as a program and was trying to follow written information provided by the lecturer albeit unsuccessfully. I hope that this may explain in case any other of those requests pop up for the document in question is in the first year of an it degree and others may also make the same mistake in the next couple of weeks. Again my apologies and i would like to assure you that there are no hard feelings from me as i know as much as the next guy how annoying that one internet troll can be, if i was in the same place i may well have done the same thing.


Thank you for your time and i hope that this hasn't bothered you to much.


Yours in truth

Peter Stone

Undergraduate Student, Bachelor of Information Technology

James Cook University, Townsville Campus

Student ID: 13288651

________________________________

**Comment by PeterStone4818** [comment]
...

[Message clipped] View entire message<http://web05.onlinevyr.host/chili/calor.php?quadratiferous=centauridium&2045966=581729a5-7af6-4421-a1cd-8137a1b27666>

**Comment by PeterStone4818** [comment]
...

[Message clipped] View entire message<http://web01.servicewkl.host/mutatory/covina.html?holtz=inharmony&81296870=2dfa5205-2837-47ec-8261-9d94c5c5e7cf>

**Comment by KeyWeeUsr** [comment]
Removed empty comment with a link to malicious website.

**Pull request closed without merging**
